project_id = "axtpbgsjbmhbuqomarcr"

[functions.bulk-sync-anime]
verify_jwt = false

[functions.anime-api]
verify_jwt = false

[functions.fetch-anime-data]
verify_jwt = false

[functions.sync-images]
verify_jwt = false

[functions.ai-recommendations]
verify_jwt = false

[functions.sync-anilist-data]
verify_jwt = false

[functions.auto-sync-all]
verify_jwt = false

[functions.intelligent-content-sync]
verify_jwt = false

[functions.schedule-cron-trigger]
verify_jwt = false

[functions.fetch-trending-data]
verify_jwt = false

[functions.auto-initialize]
verify_jwt = false

[functions.trigger-full-sync]
verify_jwt = false

[functions.fix-manga-sync]
verify_jwt = false

[functions.direct-manga-sync]
verify_jwt = false

[functions.complete-manga-sync]
verify_jwt = false

[functions.mal-manga-sync]
verify_jwt = false