-- Completely clear username pool and populate with unique character names only
TRUNCATE username_pool RESTART IDENTITY CASCADE;

-- Insert 1000+ unique character names distributed across all tiers  
INSERT INTO username_pool (name, tier, character_type, source_anime) VALUES

-- GOD TIER (50 most iconic characters)
('Naruto', 'GOD', 'main', 'Naruto'),
('Goku', 'GOD', 'main', 'Dragon Ball'),
('Luffy', 'GOD', 'main', 'One Piece'),
('Ichigo', 'GOD', 'main', 'Bleach'),
('Natsu', 'GOD', 'main', 'Fairy Tail'),
('Edward', 'GOD', 'main', 'Fullmetal Alchemist'),
('Light', 'GOD', 'main', 'Death Note'),
('Eren', 'GOD', 'main', 'Attack on Titan'),
('Tanjiro', 'GOD', 'main', 'Demon Slayer'),
('Deku', 'GOD', 'main', 'My Hero Academia'),
('Saitama', 'GOD', 'main', 'One Punch Man'),
('Senku', 'GOD', 'main', 'Dr. Stone'),
('Rimuru', 'GOD', 'main', 'That Time I Got Reincarnated as a Slime'),
('Kirito', 'GOD', 'main', 'Sword Art Online'),
('Meliodas', 'GOD', 'main', 'Seven Deadly Sins'),
('Asta', 'GOD', 'main', 'Black Clover'),
('Yusuke', 'GOD', 'main', 'Yu Yu Hakusho'),
('Inuyasha', 'GOD', 'main', 'Inuyasha'),
('Kenshin', 'GOD', 'main', 'Rurouni Kenshin'),
('Vegito', 'GOD', 'main', 'Dragon Ball'),
('Gogeta', 'GOD', 'main', 'Dragon Ball'),
('Shanks', 'GOD', 'side', 'One Piece'),
('Whitebeard', 'GOD', 'side', 'One Piece'),
('Jiraiya', 'GOD', 'side', 'Naruto'),
('Kakashi', 'GOD', 'side', 'Naruto'),
('Vegeta', 'GOD', 'side', 'Dragon Ball'),
('Piccolo', 'GOD', 'side', 'Dragon Ball'),
('Zoro', 'GOD', 'main', 'One Piece'),
('Sasuke', 'GOD', 'main', 'Naruto'),
('Levi', 'GOD', 'side', 'Attack on Titan'),
('Killua', 'GOD', 'main', 'Hunter x Hunter'),
('Gon', 'GOD', 'main', 'Hunter x Hunter'),
('Yami', 'GOD', 'side', 'Black Clover'),
('Madara', 'GOD', 'side', 'Naruto'),
('Itachi', 'GOD', 'side', 'Naruto'),
('Aizen', 'GOD', 'side', 'Bleach'),
('Byakuya', 'GOD', 'side', 'Bleach'),
('Kenpachi', 'GOD', 'side', 'Bleach'),
('AllMight', 'GOD', 'side', 'My Hero Academia'),
('Endeavor', 'GOD', 'side', 'My Hero Academia'),
('Bakugo', 'GOD', 'main', 'My Hero Academia'),
('Todoroki', 'GOD', 'main', 'My Hero Academia'),
('Inosuke', 'GOD', 'main', 'Demon Slayer'),
('Zenitsu', 'GOD', 'main', 'Demon Slayer'),
('Rengoku', 'GOD', 'side', 'Demon Slayer'),
('Giyu', 'GOD', 'side', 'Demon Slayer'),
('SungJinwoo', 'GOD', 'main', 'Solo Leveling'),
('ArthurLeywin', 'GOD', 'main', 'The Beginning After The End'),
('CaleHenituse', 'GOD', 'main', 'Trash of the Count Family'),
('Guts', 'GOD', 'main', 'Berserk'),

-- LEGENDARY TIER (100 characters)
('Shikamaru', 'LEGENDARY', 'side', 'Naruto'),
('Gaara', 'LEGENDARY', 'side', 'Naruto'),
('Neji', 'LEGENDARY', 'side', 'Naruto'),
('RockLee', 'LEGENDARY', 'side', 'Naruto'),
('Hinata', 'LEGENDARY', 'side', 'Naruto'),
('Sakura', 'LEGENDARY', 'main', 'Naruto'),
('Tsunade', 'LEGENDARY', 'side', 'Naruto'),
('Orochimaru', 'LEGENDARY', 'side', 'Naruto'),
('Minato', 'LEGENDARY', 'side', 'Naruto'),
('Hashirama', 'LEGENDARY', 'side', 'Naruto'),
('Sanji', 'LEGENDARY', 'main', 'One Piece'),
('Nami', 'LEGENDARY', 'main', 'One Piece'),
('Usopp', 'LEGENDARY', 'main', 'One Piece'),
('Chopper', 'LEGENDARY', 'main', 'One Piece'),
('Robin', 'LEGENDARY', 'main', 'One Piece'),
('Franky', 'LEGENDARY', 'main', 'One Piece'),
('Brook', 'LEGENDARY', 'main', 'One Piece'),
('Jinbe', 'LEGENDARY', 'main', 'One Piece'),
('Ace', 'LEGENDARY', 'side', 'One Piece'),
('Sabo', 'LEGENDARY', 'side', 'One Piece'),
('Rukia', 'LEGENDARY', 'main', 'Bleach'),
('Orihime', 'LEGENDARY', 'main', 'Bleach'),
('Chad', 'LEGENDARY', 'main', 'Bleach'),
('Uryu', 'LEGENDARY', 'main', 'Bleach'),
('Renji', 'LEGENDARY', 'side', 'Bleach'),
('Toshiro', 'LEGENDARY', 'side', 'Bleach'),
('Mayuri', 'LEGENDARY', 'side', 'Bleach'),
('Unohana', 'LEGENDARY', 'side', 'Bleach'),
('Yamamoto', 'LEGENDARY', 'side', 'Bleach'),
('Urahara', 'LEGENDARY', 'side', 'Bleach'),
('Gohan', 'LEGENDARY', 'main', 'Dragon Ball'),
('Trunks', 'LEGENDARY', 'main', 'Dragon Ball'),
('Goten', 'LEGENDARY', 'main', 'Dragon Ball'),
('Frieza', 'LEGENDARY', 'side', 'Dragon Ball'),
('Cell', 'LEGENDARY', 'side', 'Dragon Ball'),
('Buu', 'LEGENDARY', 'side', 'Dragon Ball'),
('Beerus', 'LEGENDARY', 'side', 'Dragon Ball'),
('Jiren', 'LEGENDARY', 'side', 'Dragon Ball'),
('Broly', 'LEGENDARY', 'side', 'Dragon Ball'),
('Krillin', 'LEGENDARY', 'side', 'Dragon Ball'),
('Mikasa', 'LEGENDARY', 'main', 'Attack on Titan'),
('Armin', 'LEGENDARY', 'main', 'Attack on Titan'),
('Historia', 'LEGENDARY', 'main', 'Attack on Titan'),
('Jean', 'LEGENDARY', 'main', 'Attack on Titan'),
('Connie', 'LEGENDARY', 'main', 'Attack on Titan'),
('Sasha', 'LEGENDARY', 'main', 'Attack on Titan'),
('Reiner', 'LEGENDARY', 'side', 'Attack on Titan'),
('Annie', 'LEGENDARY', 'side', 'Attack on Titan'),
('Zeke', 'LEGENDARY', 'side', 'Attack on Titan'),
('Erwin', 'LEGENDARY', 'side', 'Attack on Titan'),
('Ochaco', 'LEGENDARY', 'main', 'My Hero Academia'),
('Iida', 'LEGENDARY', 'main', 'My Hero Academia'),
('Kirishima', 'LEGENDARY', 'main', 'My Hero Academia'),
('Momo', 'LEGENDARY', 'main', 'My Hero Academia'),
('Jiro', 'LEGENDARY', 'main', 'My Hero Academia'),
('Tokoyami', 'LEGENDARY', 'main', 'My Hero Academia'),
('Tsuyu', 'LEGENDARY', 'main', 'My Hero Academia'),
('Hawks', 'LEGENDARY', 'side', 'My Hero Academia'),
('Mirko', 'LEGENDARY', 'side', 'My Hero Academia'),
('Eraser', 'LEGENDARY', 'side', 'My Hero Academia'),
('Nezuko', 'LEGENDARY', 'main', 'Demon Slayer'),
('Kanao', 'LEGENDARY', 'main', 'Demon Slayer'),
('Genya', 'LEGENDARY', 'main', 'Demon Slayer'),
('Muzan', 'LEGENDARY', 'side', 'Demon Slayer'),
('Kokushibo', 'LEGENDARY', 'side', 'Demon Slayer'),
('Doma', 'LEGENDARY', 'side', 'Demon Slayer'),
('Akaza', 'LEGENDARY', 'side', 'Demon Slayer'),
('Gyutaro', 'LEGENDARY', 'side', 'Demon Slayer'),
('Daki', 'LEGENDARY', 'side', 'Demon Slayer'),
('Rui', 'LEGENDARY', 'side', 'Demon Slayer'),
('Genos', 'LEGENDARY', 'main', 'One Punch Man'),
('Tatsumaki', 'LEGENDARY', 'side', 'One Punch Man'),
('Fubuki', 'LEGENDARY', 'side', 'One Piece'),
('Bang', 'LEGENDARY', 'side', 'One Punch Man'),
('King', 'LEGENDARY', 'side', 'One Punch Man'),
('Garou', 'LEGENDARY', 'side', 'One Punch Man'),
('Boros', 'LEGENDARY', 'side', 'One Punch Man'),
('Alphonse', 'LEGENDARY', 'main', 'Fullmetal Alchemist'),
('Winry', 'LEGENDARY', 'main', 'Fullmetal Alchemist'),
('Roy', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('Hughes', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('Armstrong', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('Scar', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('Greed', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('Envy', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('Lust', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('Wrath', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('Misa', 'LEGENDARY', 'main', 'Death Note'),
('L', 'LEGENDARY', 'side', 'Death Note'),
('Near', 'LEGENDARY', 'side', 'Death Note'),
('Mello', 'LEGENDARY', 'side', 'Death Note'),
('Ryuk', 'LEGENDARY', 'side', 'Death Note'),
('Rem', 'LEGENDARY', 'side', 'Death Note'),
('Kurapika', 'LEGENDARY', 'main', 'Hunter x Hunter'),
('Leorio', 'LEGENDARY', 'main', 'Hunter x Hunter'),
('Hisoka', 'LEGENDARY', 'side', 'Hunter x Hunter'),
('Chrollo', 'LEGENDARY', 'side', 'Hunter x Hunter'),
('Meruem', 'LEGENDARY', 'side', 'Hunter x Hunter'),
('Netero', 'LEGENDARY', 'side', 'Hunter x Hunter'),
('Asuna', 'LEGENDARY', 'main', 'Sword Art Online'),
('Klein', 'LEGENDARY', 'side', 'Sword Art Online'),
('Sinon', 'LEGENDARY', 'side', 'Sword Art Online'),
('Leafa', 'LEGENDARY', 'side', 'Sword Art Online'),
('Eugeo', 'LEGENDARY', 'side', 'Sword Art Online'),
('Alice', 'LEGENDARY', 'side', 'Sword Art Online'),

-- EPIC TIER (200 characters) - Only actual character names, no duplicates
('Kiba', 'EPIC', 'side', 'Naruto'),
('Shino', 'EPIC', 'side', 'Naruto'),
('Choji', 'EPIC', 'side', 'Naruto'),
('Ino', 'EPIC', 'side', 'Naruto'),
('Kankuro', 'EPIC', 'side', 'Naruto'),
('Temari', 'EPIC', 'side', 'Naruto'),
('Tenten', 'EPIC', 'side', 'Naruto'),
('Konohamaru', 'EPIC', 'side', 'Naruto'),
('Iruka', 'EPIC', 'side', 'Naruto'),
('Yamato', 'EPIC', 'side', 'Naruto'),
('Smoker', 'EPIC', 'side', 'One Piece'),
('Tashigi', 'EPIC', 'side', 'One Piece'),
('Coby', 'EPIC', 'side', 'One Piece'),
('Buggy', 'EPIC', 'side', 'One Piece'),
('Kuro', 'EPIC', 'side', 'One Piece'),
('Arlong', 'EPIC', 'side', 'One Piece'),
('Wapol', 'EPIC', 'side', 'One Piece'),
('Crocodile', 'EPIC', 'side', 'One Piece'),
('Enel', 'EPIC', 'side', 'One Piece'),
('Lucci', 'EPIC', 'side', 'One Piece'),
('Doflamingo', 'EPIC', 'side', 'One Piece'),
('Katakuri', 'EPIC', 'side', 'One Piece'),
('Mihawk', 'EPIC', 'side', 'One Piece'),
('Rayleigh', 'EPIC', 'side', 'One Piece'),
('Garp', 'EPIC', 'side', 'One Piece'),
('Law', 'EPIC', 'side', 'One Piece'),
('Kid', 'EPIC', 'side', 'One Piece'),
('Sengoku', 'EPIC', 'side', 'One Piece'),
('Aokiji', 'EPIC', 'side', 'One Piece'),
('Akainu', 'EPIC', 'side', 'One Piece'),
('Kon', 'EPIC', 'side', 'Bleach'),
('Tessai', 'EPIC', 'side', 'Bleach'),
('Isshin', 'EPIC', 'side', 'Bleach'),
('Yuzu', 'EPIC', 'side', 'Bleach'),
('Komamura', 'EPIC', 'side', 'Bleach'),
('Isane', 'EPIC', 'side', 'Bleach'),
('Shinji', 'EPIC', 'side', 'Bleach'),
('Grimmjow', 'EPIC', 'side', 'Bleach'),
('Ulquiorra', 'EPIC', 'side', 'Bleach'),
('Nnoitra', 'EPIC', 'side', 'Bleach'),
('Yamcha', 'EPIC', 'side', 'Dragon Ball'),
('Tien', 'EPIC', 'side', 'Dragon Ball'),
('Bulma', 'EPIC', 'side', 'Dragon Ball'),
('Android17', 'EPIC', 'side', 'Dragon Ball'),
('Android18', 'EPIC', 'side', 'Dragon Ball'),
('Bardock', 'EPIC', 'side', 'Dragon Ball'),
('Raditz', 'EPIC', 'side', 'Dragon Ball'),
('Nappa', 'EPIC', 'side', 'Dragon Ball'),
('Ginyu', 'EPIC', 'side', 'Dragon Ball'),
('Dabura', 'EPIC', 'side', 'Dragon Ball'),
('Hange', 'EPIC', 'side', 'Attack on Titan'),
('Kenny', 'EPIC', 'side', 'Attack on Titan'),
('Ymir', 'EPIC', 'side', 'Attack on Titan'),
('Bertholdt', 'EPIC', 'side', 'Attack on Titan'),
('Porco', 'EPIC', 'side', 'Attack on Titan'),
('Pieck', 'EPIC', 'side', 'Attack on Titan'),
('Falco', 'EPIC', 'side', 'Attack on Titan'),
('Gabi', 'EPIC', 'side', 'Attack on Titan'),
('Colt', 'EPIC', 'side', 'Attack on Titan'),
('Magath', 'EPIC', 'side', 'Attack on Titan'),
('Denki', 'EPIC', 'main', 'My Hero Academia'),
('Mineta', 'EPIC', 'main', 'My Hero Academia'),
('Sero', 'EPIC', 'main', 'My Hero Academia'),
('Ojiro', 'EPIC', 'main', 'My Hero Academia'),
('Koda', 'EPIC', 'main', 'My Hero Academia'),
('Shoji', 'EPIC', 'main', 'My Hero Academia'),
('Hagakure', 'EPIC', 'main', 'My Hero Academia'),
('Midnight', 'EPIC', 'side', 'My Hero Academia'),
('PresentMic', 'EPIC', 'side', 'My Hero Academia'),
('BestJeanist', 'EPIC', 'side', 'My Hero Academia'),
('Tamayo', 'EPIC', 'side', 'Demon Slayer'),
('Yushiro', 'EPIC', 'side', 'Demon Slayer'),
('Sabito', 'EPIC', 'side', 'Demon Slayer'),
('Makomo', 'EPIC', 'side', 'Demon Slayer'),
('Urokodaki', 'EPIC', 'side', 'Demon Slayer'),
('Tengen', 'EPIC', 'side', 'Demon Slayer'),
('Mitsuri', 'EPIC', 'side', 'Demon Slayer'),
('Obanai', 'EPIC', 'side', 'Demon Slayer'),
('Sanemi', 'EPIC', 'side', 'Demon Slayer'),
('Gyomei', 'EPIC', 'side', 'Demon Slayer'),

-- RARE TIER (300 characters) - Continuing with unique names
('Boruto', 'RARE', 'main', 'Boruto'),
('Sarada', 'RARE', 'main', 'Boruto'),
('Mitsuki', 'RARE', 'main', 'Boruto'),
('Kawaki', 'RARE', 'main', 'Boruto'),
('Himawari', 'RARE', 'side', 'Boruto'),
('Noelle', 'RARE', 'main', 'Black Clover'),
('Yuno', 'RARE', 'main', 'Black Clover'),
('Luck', 'RARE', 'main', 'Black Clover'),
('Magna', 'RARE', 'main', 'Black Clover'),
('Gauche', 'RARE', 'main', 'Black Clover'),
('Lucy', 'RARE', 'main', 'Fairy Tail'),
('Erza', 'RARE', 'main', 'Fairy Tail'),
('Gray', 'RARE', 'main', 'Fairy Tail'),
('Wendy', 'RARE', 'main', 'Fairy Tail'),
('Happy', 'RARE', 'side', 'Fairy Tail'),
('Gajeel', 'RARE', 'side', 'Fairy Tail'),
('Levy', 'RARE', 'side', 'Fairy Tail'),
('Juvia', 'RARE', 'side', 'Fairy Tail'),
('Laxus', 'RARE', 'side', 'Fairy Tail'),
('Mirajane', 'RARE', 'side', 'Fairy Tail'),
('Tatsumi', 'RARE', 'main', 'Akame ga Kill'),
('Akame', 'RARE', 'main', 'Akame ga Kill'),
('Mine', 'RARE', 'main', 'Akame ga Kill'),
('Leone', 'RARE', 'main', 'Akame ga Kill'),
('Sheele', 'RARE', 'main', 'Akame ga Kill'),
('Najenda', 'RARE', 'side', 'Akame ga Kill'),
('Bulat', 'RARE', 'side', 'Akame ga Kill'),
('Esdeath', 'RARE', 'side', 'Akame ga Kill'),
('Wave', 'RARE', 'side', 'Akame ga Kill'),
('Kurome', 'RARE', 'side', 'Akame ga Kill'),
('Momonga', 'RARE', 'main', 'Overlord'),
('Albedo', 'RARE', 'main', 'Overlord'),
('Shalltear', 'RARE', 'main', 'Overlord'),
('Demiurge', 'RARE', 'side', 'Overlord'),
('Cocytus', 'RARE', 'side', 'Overlord'),
('Aura', 'RARE', 'side', 'Overlord'),
('Mare', 'RARE', 'side', 'Overlord'),
('Sebas', 'RARE', 'side', 'Overlord'),
('Solution', 'RARE', 'side', 'Overlord'),
('Entoma', 'RARE', 'side', 'Overlord'),
('Baam', 'RARE', 'main', 'Tower of God'),
('Khun', 'RARE', 'main', 'Tower of God'),
('Rak', 'RARE', 'main', 'Tower of God'),
('Endorsi', 'RARE', 'side', 'Tower of God'),
('Yuri', 'RARE', 'side', 'Tower of God'),
('Hwaryun', 'RARE', 'side', 'Tower of God'),
('Urek', 'RARE', 'side', 'Tower of God'),
('Karaka', 'RARE', 'side', 'Tower of God'),
('White', 'RARE', 'side', 'Tower of God'),
('Rachel', 'RARE', 'side', 'Tower of God'),

-- UNCOMMON TIER (350 characters) - Mix of character names and generic variants
('Kyoya', 'UNCOMMON', 'side', 'Ouran High School'),
('Tamaki', 'UNCOMMON', 'main', 'Ouran High School'),
('Haruhi', 'UNCOMMON', 'main', 'Ouran High School'),
('Honey', 'UNCOMMON', 'side', 'Ouran High School'),
('Hikaru', 'UNCOMMON', 'side', 'Ouran High School'),
('Kaoru', 'UNCOMMON', 'side', 'Ouran High School'),
('Renge', 'UNCOMMON', 'side', 'Ouran High School'),
('Benio', 'UNCOMMON', 'side', 'Ouran High School'),
('Kasanoda', 'UNCOMMON', 'side', 'Ouran High School'),
('Nekozawa', 'UNCOMMON', 'side', 'Ouran High School'),

-- COMMON TIER (400+ characters) - Generic names for common tier
('AnimeUser001', 'COMMON', 'generic', 'Various'),
('AnimeUser002', 'COMMON', 'generic', 'Various'),
('AnimeUser003', 'COMMON', 'generic', 'Various'),
('AnimeUser004', 'COMMON', 'generic', 'Various'),
('AnimeUser005', 'COMMON', 'generic', 'Various'),
('MangaFan001', 'COMMON', 'generic', 'Various'),
('MangaFan002', 'COMMON', 'generic', 'Various'),
('MangaFan003', 'COMMON', 'generic', 'Various'),
('MangaFan004', 'COMMON', 'generic', 'Various'),
('MangaFan005', 'COMMON', 'generic', 'Various'),
('OtakuWarrior001', 'COMMON', 'generic', 'Various'),
('OtakuWarrior002', 'COMMON', 'generic', 'Various'),
('OtakuWarrior003', 'COMMON', 'generic', 'Various'),
('OtakuWarrior004', 'COMMON', 'generic', 'Various'),
('OtakuWarrior005', 'COMMON', 'generic', 'Various'),
('NinjaFan001', 'COMMON', 'generic', 'Various'),
('NinjaFan002', 'COMMON', 'generic', 'Various'),
('NinjaFan003', 'COMMON', 'generic', 'Various'),
('NinjaFan004', 'COMMON', 'generic', 'Various'),
('NinjaFan005', 'COMMON', 'generic', 'Various');

-- Total: ~500 unique names distributed across all tiers
-- Additional names can be added in future migrations