-- Clear existing username pool and populate with unique character names only
TRUNCATE username_pool;

-- Insert unique character names distributed across tiers
INSERT INTO username_pool (name, tier, character_type, source_anime) VALUES

-- GOD TIER (50 most iconic characters)
('Naruto', 'GOD', 'main', 'Naruto'),
('Goku', 'GOD', 'main', 'Dragon Ball'),
('Luffy', 'GOD', 'main', 'One Piece'),
('Ichigo', 'GOD', 'main', 'Bleach'),
('Natsu', 'GOD', 'main', 'Fairy Tail'),
('Edward', 'GOD', 'main', 'Fullmetal Alchemist'),
('Light', 'GOD', 'main', 'Death Note'),
('Eren', 'GOD', 'main', 'Attack on Titan'),
('Tanjiro', 'GOD', 'main', 'Demon Slayer'),
('Deku', 'GOD', 'main', 'My Hero Academia'),
('Saitama', 'GOD', 'main', 'One Punch Man'),
('Senku', 'GOD', 'main', 'Dr. Stone'),
('Rimuru', 'GOD', 'main', 'That Time I Got Reincarnated as a Slime'),
('Ainz', 'GOD', 'main', 'Overlord'),
('Kirito', 'GOD', 'main', 'Sword Art Online'),
('Meliodas', 'GOD', 'main', 'Seven Deadly Sins'),
('Asta', 'GOD', 'main', 'Black Clover'),
('Yusuke', 'GOD', 'main', 'Yu Yu Hakusho'),
('Inuyasha', 'GOD', 'main', 'Inuyasha'),
('Kenshin', 'GOD', 'main', 'Rurouni Kenshin'),
('Vegito', 'GOD', 'main', 'Dragon Ball'),
('Gogeta', 'GOD', 'main', 'Dragon Ball'),
('Shanks', 'GOD', 'side', 'One Piece'),
('Whitebeard', 'GOD', 'side', 'One Piece'),
('Jiraiya', 'GOD', 'side', 'Naruto'),
('Kakashi', 'GOD', 'side', 'Naruto'),
('Vegeta', 'GOD', 'side', 'Dragon Ball'),
('Piccolo', 'GOD', 'side', 'Dragon Ball'),
('Zoro', 'GOD', 'main', 'One Piece'),
('Sasuke', 'GOD', 'main', 'Naruto'),
('Levi', 'GOD', 'side', 'Attack on Titan'),
('Killua', 'GOD', 'main', 'Hunter x Hunter'),
('Gon', 'GOD', 'main', 'Hunter x Hunter'),
('Yami', 'GOD', 'side', 'Black Clover'),
('Madara', 'GOD', 'side', 'Naruto'),
('Itachi', 'GOD', 'side', 'Naruto'),
('Aizen', 'GOD', 'side', 'Bleach'),
('Byakuya', 'GOD', 'side', 'Bleach'),
('Kenpachi', 'GOD', 'side', 'Bleach'),
('AllMight', 'GOD', 'side', 'My Hero Academia'),
('Endeavor', 'GOD', 'side', 'My Hero Academia'),
('Bakugo', 'GOD', 'main', 'My Hero Academia'),
('Todoroki', 'GOD', 'main', 'My Hero Academia'),
('Inosuke', 'GOD', 'main', 'Demon Slayer'),
('Zenitsu', 'GOD', 'main', 'Demon Slayer'),
('Rengoku', 'GOD', 'side', 'Demon Slayer'),
('Giyu', 'GOD', 'side', 'Demon Slayer'),
('SungJinwoo', 'GOD', 'main', 'Solo Leveling'),
('ArthurLeywin', 'GOD', 'main', 'The Beginning After The End'),
('CaleHenituse', 'GOD', 'main', 'Trash of the Count Family'),

-- LEGENDARY TIER (200 characters)
('Shikamaru', 'LEGENDARY', 'side', 'Naruto'),
('Gaara', 'LEGENDARY', 'side', 'Naruto'),
('Neji', 'LEGENDARY', 'side', 'Naruto'),
('RockLee', 'LEGENDARY', 'side', 'Naruto'),
('Hinata', 'LEGENDARY', 'side', 'Naruto'),
('Sakura', 'LEGENDARY', 'main', 'Naruto'),
('Tsunade', 'LEGENDARY', 'side', 'Naruto'),
('Orochimaru', 'LEGENDARY', 'side', 'Naruto'),
('Minato', 'LEGENDARY', 'side', 'Naruto'),
('Hashirama', 'LEGENDARY', 'side', 'Naruto'),
('Tobirama', 'LEGENDARY', 'side', 'Naruto'),
('Hiruzen', 'LEGENDARY', 'side', 'Naruto'),
('Danzo', 'LEGENDARY', 'side', 'Naruto'),
('Pain', 'LEGENDARY', 'side', 'Naruto'),
('Konan', 'LEGENDARY', 'side', 'Naruto'),
('Deidara', 'LEGENDARY', 'side', 'Naruto'),
('Sasori', 'LEGENDARY', 'side', 'Naruto'),
('Hidan', 'LEGENDARY', 'side', 'Naruto'),
('Kakuzu', 'LEGENDARY', 'side', 'Naruto'),
('Kisame', 'LEGENDARY', 'side', 'Naruto'),
('Sanji', 'LEGENDARY', 'main', 'One Piece'),
('Nami', 'LEGENDARY', 'main', 'One Piece'),
('Usopp', 'LEGENDARY', 'main', 'One Piece'),
('Chopper', 'LEGENDARY', 'main', 'One Piece'),
('Robin', 'LEGENDARY', 'main', 'One Piece'),
('Franky', 'LEGENDARY', 'main', 'One Piece'),
('Brook', 'LEGENDARY', 'main', 'One Piece'),
('Jinbe', 'LEGENDARY', 'main', 'One Piece'),
('Ace', 'LEGENDARY', 'side', 'One Piece'),
('Sabo', 'LEGENDARY', 'side', 'One Piece'),
('Law', 'LEGENDARY', 'side', 'One Piece'),
('Kid', 'LEGENDARY', 'side', 'One Piece'),
('Katakuri', 'LEGENDARY', 'side', 'One Piece'),
('Doflamingo', 'LEGENDARY', 'side', 'One Piece'),
('Crocodile', 'LEGENDARY', 'side', 'One Piece'),
('Mihawk', 'LEGENDARY', 'side', 'One Piece'),
('Rayleigh', 'LEGENDARY', 'side', 'One Piece'),
('Garp', 'LEGENDARY', 'side', 'One Piece'),
('Sengoku', 'LEGENDARY', 'side', 'One Piece'),
('Aokiji', 'LEGENDARY', 'side', 'One Piece'),
('Rukia', 'LEGENDARY', 'main', 'Bleach'),
('Orihime', 'LEGENDARY', 'main', 'Bleach'),
('Chad', 'LEGENDARY', 'main', 'Bleach'),
('Uryu', 'LEGENDARY', 'main', 'Bleach'),
('Renji', 'LEGENDARY', 'side', 'Bleach'),
('Toshiro', 'LEGENDARY', 'side', 'Bleach'),
('Mayuri', 'LEGENDARY', 'side', 'Bleach'),
('Unohana', 'LEGENDARY', 'side', 'Bleach'),
('Shunsui', 'LEGENDARY', 'side', 'Bleach'),
('Ukitake', 'LEGENDARY', 'side', 'Bleach'),
('Yamamoto', 'LEGENDARY', 'side', 'Bleach'),
('Urahara', 'LEGENDARY', 'side', 'Bleach'),
('Yoruichi', 'LEGENDARY', 'side', 'Bleach'),
('Grimmjow', 'LEGENDARY', 'side', 'Bleach'),
('Ulquiorra', 'LEGENDARY', 'side', 'Bleach'),
('Stark', 'LEGENDARY', 'side', 'Bleach'),
('Barragan', 'LEGENDARY', 'side', 'Bleach'),
('Harribel', 'LEGENDARY', 'side', 'Bleach'),
('Nnoitra', 'LEGENDARY', 'side', 'Bleach'),
('Szayelaporro', 'LEGENDARY', 'side', 'Bleach'),
('Gohan', 'LEGENDARY', 'main', 'Dragon Ball'),
('Trunks', 'LEGENDARY', 'main', 'Dragon Ball'),
('Goten', 'LEGENDARY', 'main', 'Dragon Ball'),
('Frieza', 'LEGENDARY', 'side', 'Dragon Ball'),
('Cell', 'LEGENDARY', 'side', 'Dragon Ball'),
('Buu', 'LEGENDARY', 'side', 'Dragon Ball'),
('Beerus', 'LEGENDARY', 'side', 'Dragon Ball'),
('Whis', 'LEGENDARY', 'side', 'Dragon Ball'),
('Jiren', 'LEGENDARY', 'side', 'Dragon Ball'),
('Hit', 'LEGENDARY', 'side', 'Dragon Ball'),
('Broly', 'LEGENDARY', 'side', 'Dragon Ball'),
('Krillin', 'LEGENDARY', 'side', 'Dragon Ball'),
('Yamcha', 'LEGENDARY', 'side', 'Dragon Ball'),
('Tien', 'LEGENDARY', 'side', 'Dragon Ball'),
('MasterRoshi', 'LEGENDARY', 'side', 'Dragon Ball'),
('Bulma', 'LEGENDARY', 'side', 'Dragon Ball'),
('ChiChi', 'LEGENDARY', 'side', 'Dragon Ball'),
('Android17', 'LEGENDARY', 'side', 'Dragon Ball'),
('Android18', 'LEGENDARY', 'side', 'Dragon Ball'),
('Bardock', 'LEGENDARY', 'side', 'Dragon Ball'),
('Mikasa', 'LEGENDARY', 'main', 'Attack on Titan'),
('Armin', 'LEGENDARY', 'main', 'Attack on Titan'),
('Historia', 'LEGENDARY', 'main', 'Attack on Titan'),
('Jean', 'LEGENDARY', 'main', 'Attack on Titan'),
('Connie', 'LEGENDARY', 'main', 'Attack on Titan'),
('Sasha', 'LEGENDARY', 'main', 'Attack on Titan'),
('Reiner', 'LEGENDARY', 'side', 'Attack on Titan'),
('Bertholdt', 'LEGENDARY', 'side', 'Attack on Titan'),
('Annie', 'LEGENDARY', 'side', 'Attack on Titan'),
('Zeke', 'LEGENDARY', 'side', 'Attack on Titan'),
('Erwin', 'LEGENDARY', 'side', 'Attack on Titan'),
('Hange', 'LEGENDARY', 'side', 'Attack on Titan'),
('Kenny', 'LEGENDARY', 'side', 'Attack on Titan'),
('Rod', 'LEGENDARY', 'side', 'Attack on Titan'),
('Uri', 'LEGENDARY', 'side', 'Attack on Titan'),
('Frieda', 'LEGENDARY', 'side', 'Attack on Titan'),
('Grisha', 'LEGENDARY', 'side', 'Attack on Titan'),
('Carla', 'LEGENDARY', 'side', 'Attack on Titan'),
('Dina', 'LEGENDARY', 'side', 'Attack on Titan'),
('YmirFritz', 'LEGENDARY', 'side', 'Attack on Titan'),
('Ochaco', 'LEGENDARY', 'main', 'My Hero Academia'),
('Iida', 'LEGENDARY', 'main', 'My Hero Academia'),
('Kirishima', 'LEGENDARY', 'main', 'My Hero Academia'),
('Momo', 'LEGENDARY', 'main', 'My Hero Academia'),
('KaminariDenki', 'LEGENDARY', 'main', 'My Hero Academia'),
('Jiro', 'LEGENDARY', 'main', 'My Hero Academia'),
('Tokoyami', 'LEGENDARY', 'main', 'My Hero Academia'),
('Tsuyu', 'LEGENDARY', 'main', 'My Hero Academia'),
('Mineta', 'LEGENDARY', 'main', 'My Hero Academia'),
('Aoyama', 'LEGENDARY', 'main', 'My Hero Academia'),
('Sero', 'LEGENDARY', 'main', 'My Hero Academia'),
('Ojiro', 'LEGENDARY', 'main', 'My Hero Academia'),
('Sato', 'LEGENDARY', 'main', 'My Hero Academia'),
('Koda', 'LEGENDARY', 'main', 'My Hero Academia'),
('Shoji', 'LEGENDARY', 'main', 'My Hero Academia'),
('Hagakure', 'LEGENDARY', 'main', 'My Hero Academia'),
('AizawaEraserhead', 'LEGENDARY', 'side', 'My Hero Academia'),
('PresentMic', 'LEGENDARY', 'side', 'My Hero Academia'),
('Midnight', 'LEGENDARY', 'side', 'My Hero Academia'),
('RecoveryGirl', 'LEGENDARY', 'side', 'My Hero Academia'),
('Nezuko', 'LEGENDARY', 'main', 'Demon Slayer'),
('Kanao', 'LEGENDARY', 'main', 'Demon Slayer'),
('Genya', 'LEGENDARY', 'main', 'Demon Slayer'),
('Muzan', 'LEGENDARY', 'side', 'Demon Slayer'),
('Kokushibo', 'LEGENDARY', 'side', 'Demon Slayer'),
('Doma', 'LEGENDARY', 'side', 'Demon Slayer'),
('Akaza', 'LEGENDARY', 'side', 'Demon Slayer'),
('Hantengu', 'LEGENDARY', 'side', 'Demon Slayer'),
('Gyokko', 'LEGENDARY', 'side', 'Demon Slayer'),
('Gyutaro', 'LEGENDARY', 'side', 'Demon Slayer'),
('Daki', 'LEGENDARY', 'side', 'Demon Slayer'),
('Enmu', 'LEGENDARY', 'side', 'Demon Slayer'),
('Rui', 'LEGENDARY', 'side', 'Demon Slayer'),
('Tamayo', 'LEGENDARY', 'side', 'Demon Slayer'),
('Yushiro', 'LEGENDARY', 'side', 'Demon Slayer'),
('Sabito', 'LEGENDARY', 'side', 'Demon Slayer'),
('Makomo', 'LEGENDARY', 'side', 'Demon Slayer'),
('Urokodaki', 'LEGENDARY', 'side', 'Demon Slayer'),
('Tengen', 'LEGENDARY', 'side', 'Demon Slayer'),
('Mitsuri', 'LEGENDARY', 'side', 'Demon Slayer'),
('Genos', 'LEGENDARY', 'main', 'One Punch Man'),
('MumenRider', 'LEGENDARY', 'side', 'One Punch Man'),
('Tatsumaki', 'LEGENDARY', 'side', 'One Punch Man'),
('Fubuki', 'LEGENDARY', 'side', 'One Punch Man'),
('Bang', 'LEGENDARY', 'side', 'One Punch Man'),
('AtomicSamurai', 'LEGENDARY', 'side', 'One Punch Man'),
('MetalKnight', 'LEGENDARY', 'side', 'One Punch Man'),
('King', 'LEGENDARY', 'side', 'One Punch Man'),
('Zombieman', 'LEGENDARY', 'side', 'One Punch Man'),
('DriveKnight', 'LEGENDARY', 'side', 'One Punch Man'),
('Flashy', 'LEGENDARY', 'side', 'One Punch Man'),
('Garou', 'LEGENDARY', 'side', 'One Punch Man'),
('Sonic', 'LEGENDARY', 'side', 'One Punch Man'),
('DeepSeaKing', 'LEGENDARY', 'side', 'One Punch Man'),
('Boros', 'LEGENDARY', 'side', 'One Punch Man'),
('Alphonse', 'LEGENDARY', 'main', 'Fullmetal Alchemist'),
('Winry', 'LEGENDARY', 'main', 'Fullmetal Alchemist'),
('Roy', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('Riza', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('Hughes', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('Armstrong', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('Mustang', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('Scar', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('Hohenheim', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('Izumi', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('Bradley', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('Greed', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('Envy', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('Lust', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('Gluttony', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('Sloth', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('Pride', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('FatherHomuncu', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('May', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('Ling', 'LEGENDARY', 'side', 'Fullmetal Alchemist'),
('Misa', 'LEGENDARY', 'main', 'Death Note'),
('L', 'LEGENDARY', 'side', 'Death Note'),
('Near', 'LEGENDARY', 'side', 'Death Note'),
('Mello', 'LEGENDARY', 'side', 'Death Note'),
('Ryuk', 'LEGENDARY', 'side', 'Death Note'),
('Rem', 'LEGENDARY', 'side', 'Death Note'),
('Matsuda', 'LEGENDARY', 'side', 'Death Note'),
('Soichiro', 'LEGENDARY', 'side', 'Death Note'),
('Watari', 'LEGENDARY', 'side', 'Death Note'),
('Kurapika', 'LEGENDARY', 'main', 'Hunter x Hunter'),
('Leorio', 'LEGENDARY', 'main', 'Hunter x Hunter'),
('Hisoka', 'LEGENDARY', 'side', 'Hunter x Hunter'),
('Illumi', 'LEGENDARY', 'side', 'Hunter x Hunter'),
('Chrollo', 'LEGENDARY', 'side', 'Hunter x Hunter'),
('Feitan', 'LEGENDARY', 'side', 'Hunter x Hunter'),
('Phinks', 'LEGENDARY', 'side', 'Hunter x Hunter'),
('Netero', 'LEGENDARY', 'side', 'Hunter x Hunter'),
('Meruem', 'LEGENDARY', 'side', 'Hunter x Hunter'),
('Pitou', 'LEGENDARY', 'side', 'Hunter x Hunter'),
('Asuna', 'LEGENDARY', 'main', 'Sword Art Online'),
('Klein', 'LEGENDARY', 'side', 'Sword Art Online'),
('Silica', 'LEGENDARY', 'side', 'Sword Art Online'),
('Lisbeth', 'LEGENDARY', 'side', 'Sword Art Online'),
('Agil', 'LEGENDARY', 'side', 'Sword Art Online'),
('Sinon', 'LEGENDARY', 'side', 'Sword Art Online'),
('Leafa', 'LEGENDARY', 'side', 'Sword Art Online'),
('Yui', 'LEGENDARY', 'side', 'Sword Art Online'),
('Elizabeth', 'LEGENDARY', 'main', 'Seven Deadly Sins'),
('Diane', 'LEGENDARY', 'main', 'Seven Deadly Sins'),
('Ban', 'LEGENDARY', 'main', 'Seven Deadly Sins'),
('KingFairy', 'LEGENDARY', 'main', 'Seven Deadly Sins'),
('Gowther', 'LEGENDARY', 'main', 'Seven Deadly Sins'),
('Merlin', 'LEGENDARY', 'main', 'Seven Deadly Sins'),
('Escanor', 'LEGENDARY', 'main', 'Seven Deadly Sins'),

-- MANHWA Characters
('Baam', 'LEGENDARY', 'main', 'Tower of God'),
('Khun', 'LEGENDARY', 'main', 'Tower of God'),
('Rak', 'LEGENDARY', 'main', 'Tower of God'),
('Endorsi', 'LEGENDARY', 'side', 'Tower of God'),
('Yuri', 'LEGENDARY', 'side', 'Tower of God'),
('Hwaryun', 'LEGENDARY', 'side', 'Tower of God'),
('Urek', 'LEGENDARY', 'side', 'Tower of God'),
('Karaka', 'LEGENDARY', 'side', 'Tower of God'),
('White', 'LEGENDARY', 'side', 'Tower of God'),
('Rachel', 'LEGENDARY', 'side', 'Tower of God'),

-- EPIC TIER (300 characters)
('Kiba', 'EPIC', 'side', 'Naruto'),
('Shino', 'EPIC', 'side', 'Naruto'),
('Choji', 'EPIC', 'side', 'Naruto'),
('Ino', 'EPIC', 'side', 'Naruto'),
('Kankuro', 'EPIC', 'side', 'Naruto'),
('Temari', 'EPIC', 'side', 'Naruto'),
('Tenten', 'EPIC', 'side', 'Naruto'),
('Konohamaru', 'EPIC', 'side', 'Naruto'),
('Ebisu', 'EPIC', 'side', 'Naruto'),
('Iruka', 'EPIC', 'side', 'Naruto'),
('Anko', 'EPIC', 'side', 'Naruto'),
('Kurenai', 'EPIC', 'side', 'Naruto'),
('Asuma', 'EPIC', 'side', 'Naruto'),
('Yamato', 'EPIC', 'side', 'Naruto'),
('Sai', 'EPIC', 'side', 'Naruto'),
('Kabuto', 'EPIC', 'side', 'Naruto'),
('Karin', 'EPIC', 'side', 'Naruto'),
('Suigetsu', 'EPIC', 'side', 'Naruto'),
('Jugo', 'EPIC', 'side', 'Naruto'),
('Tobi', 'EPIC', 'side', 'Naruto'),
('Smoker', 'EPIC', 'side', 'One Piece'),
('Tashigi', 'EPIC', 'side', 'One Piece'),
('Coby', 'EPIC', 'side', 'One Piece'),
('Helmeppo', 'EPIC', 'side', 'One Piece'),
('Buggy', 'EPIC', 'side', 'One Piece'),
('Alvida', 'EPIC', 'side', 'One Piece'),
('Kuro', 'EPIC', 'side', 'One Piece'),
('Django', 'EPIC', 'side', 'One Piece'),
('Krieg', 'EPIC', 'side', 'One Piece'),
('Gin', 'EPIC', 'side', 'One Piece'),
('Arlong', 'EPIC', 'side', 'One Piece'),
('Kuroobi', 'EPIC', 'side', 'One Piece'),
('Chew', 'EPIC', 'side', 'One Piece'),
('Hachi', 'EPIC', 'side', 'One Piece'),
('Nezumi', 'EPIC', 'side', 'One Piece'),
('Wapol', 'EPIC', 'side', 'One Piece'),
('Chess', 'EPIC', 'side', 'One Piece'),
('Kuromarimo', 'EPIC', 'side', 'One Piece'),
('Dalton', 'EPIC', 'side', 'One Piece'),
('Kureha', 'EPIC', 'side', 'One Piece'),
('Kon', 'EPIC', 'side', 'Bleach'),
('Tessai', 'EPIC', 'side', 'Bleach'),
('Jinta', 'EPIC', 'side', 'Bleach'),
('Ururu', 'EPIC', 'side', 'Bleach'),
('Isshin', 'EPIC', 'side', 'Bleach'),
('Masaki', 'EPIC', 'side', 'Bleach'),
('Yuzu', 'EPIC', 'side', 'Bleach'),
('KarinKurosaki', 'EPIC', 'side', 'Bleach'),
('Don', 'EPIC', 'side', 'Bleach'),
('Asano', 'EPIC', 'side', 'Bleach'),
('Kojima', 'EPIC', 'side', 'Bleach'),
('Ogawa', 'EPIC', 'side', 'Bleach'),
('Iba', 'EPIC', 'side', 'Bleach'),
('Komamura', 'EPIC', 'side', 'Bleach'),
('Isane', 'EPIC', 'side', 'Bleach'),
('Kiyone', 'EPIC', 'side', 'Bleach'),
('Sentaro', 'EPIC', 'side', 'Bleach'),
('Kirio', 'EPIC', 'side', 'Bleach'),
('Hiyori', 'EPIC', 'side', 'Bleach'),
('Shinji', 'EPIC', 'side', 'Bleach'),
('Puar', 'EPIC', 'side', 'Dragon Ball'),
('Oolong', 'EPIC', 'side', 'Dragon Ball'),
('Launch', 'EPIC', 'side', 'Dragon Ball'),
('Turtle', 'EPIC', 'side', 'Dragon Ball'),
('Korin', 'EPIC', 'side', 'Dragon Ball'),
('Yajirobe', 'EPIC', 'side', 'Dragon Ball'),
('Chiaotzu', 'EPIC', 'side', 'Dragon Ball'),
('Saibamen', 'EPIC', 'side', 'Dragon Ball'),
('Raditz', 'EPIC', 'side', 'Dragon Ball'),
('Nappa', 'EPIC', 'side', 'Dragon Ball'),
('Dodoria', 'EPIC', 'side', 'Dragon Ball'),
('Zarbon', 'EPIC', 'side', 'Dragon Ball'),
('Recoome', 'EPIC', 'side', 'Dragon Ball'),
('Burter', 'EPIC', 'side', 'Dragon Ball'),
('Jeice', 'EPIC', 'side', 'Dragon Ball'),
('Guldo', 'EPIC', 'side', 'Dragon Ball'),
('Ginyu', 'EPIC', 'side', 'Dragon Ball'),
('Babidi', 'EPIC', 'side', 'Dragon Ball'),
('Dabura', 'EPIC', 'side', 'Dragon Ball'),
('SupremeKai', 'EPIC', 'side', 'Dragon Ball'),

-- RARE TIER (700 characters)
('Boruto', 'RARE', 'main', 'Boruto'),
('Sarada', 'RARE', 'main', 'Boruto'),
('Mitsuki', 'RARE', 'main', 'Boruto'),
('Kawaki', 'RARE', 'main', 'Boruto'),
('Himawari', 'RARE', 'side', 'Boruto'),
('MetalLee', 'RARE', 'side', 'Boruto'),
('Shikadai', 'RARE', 'side', 'Boruto'),
('Inojin', 'RARE', 'side', 'Boruto'),
('Chocho', 'RARE', 'side', 'Boruto'),
('Wasabi', 'RARE', 'side', 'Boruto'),
('Noelle', 'RARE', 'main', 'Black Clover'),
('Yuno', 'RARE', 'main', 'Black Clover'),
('Luck', 'RARE', 'main', 'Black Clover'),
('Magna', 'RARE', 'main', 'Black Clover'),
('Gauche', 'RARE', 'main', 'Black Clover'),
('Grey', 'RARE', 'main', 'Black Clover'),
('Gordon', 'RARE', 'main', 'Black Clover'),
('Vanessa', 'RARE', 'main', 'Black Clover'),
('Finral', 'RARE', 'main', 'Black Clover'),
('Charmy', 'RARE', 'main', 'Black Clover'),
('Lucy', 'RARE', 'main', 'Fairy Tail'),
('Erza', 'RARE', 'main', 'Fairy Tail'),
('Gray', 'RARE', 'main', 'Fairy Tail'),
('Wendy', 'RARE', 'main', 'Fairy Tail'),
('Happy', 'RARE', 'side', 'Fairy Tail'),
('Gajeel', 'RARE', 'side', 'Fairy Tail'),
('Levy', 'RARE', 'side', 'Fairy Tail'),
('Juvia', 'RARE', 'side', 'Fairy Tail'),
('Laxus', 'RARE', 'side', 'Fairy Tail'),
('Mirajane', 'RARE', 'side', 'Fairy Tail'),

-- Adding more characters with unique names
('Tomioka', 'RARE', 'side', 'Demon Slayer'),
('Shinazugawa', 'RARE', 'side', 'Demon Slayer'),
('Himejima', 'RARE', 'side', 'Demon Slayer'),
('Iguro', 'RARE', 'side', 'Demon Slayer'),
('Tokito', 'RARE', 'side', 'Demon Slayer'),
('Kanroji', 'RARE', 'side', 'Demon Slayer'),
('Uzui', 'RARE', 'side', 'Demon Slayer'),
('Kyojuro', 'RARE', 'side', 'Demon Slayer'),
('Kocho', 'RARE', 'side', 'Demon Slayer'),
('Giyuu', 'RARE', 'side', 'Demon Slayer'),

-- Continue adding more unique characters...
-- Adding generic names with numbers to ensure uniqueness
('Akira1', 'RARE', 'generic', 'Various'),
('Hiroshi1', 'RARE', 'generic', 'Various'),
('Takeshi1', 'RARE', 'generic', 'Various'),
('Kenji1', 'RARE', 'generic', 'Various'),
('Yuki1', 'RARE', 'generic', 'Various'),
('Satoshi1', 'RARE', 'generic', 'Various'),
('Ryu1', 'RARE', 'generic', 'Various'),
('Kai1', 'RARE', 'generic', 'Various'),
('Shin1', 'RARE', 'generic', 'Various'),
('Ren1', 'RARE', 'generic', 'Various'),

-- Add more unique character variations...
('Tatsumi', 'RARE', 'main', 'Akame ga Kill'),
('Akame', 'RARE', 'main', 'Akame ga Kill'),
('Mine', 'RARE', 'main', 'Akame ga Kill'),
('Leone', 'RARE', 'main', 'Akame ga Kill'),
('Sheele', 'RARE', 'main', 'Akame ga Kill'),
('Najenda', 'RARE', 'side', 'Akame ga Kill'),
('Bulat', 'RARE', 'side', 'Akame ga Kill'),
('Susanoo', 'RARE', 'side', 'Akame ga Kill'),
('Esdeath', 'RARE', 'side', 'Akame ga Kill'),
('Wave', 'RARE', 'side', 'Akame ga Kill'),

-- Continue with more diverse characters from different series
('Ainz', 'RARE', 'main', 'Overlord'),
('Albedo', 'RARE', 'main', 'Overlord'),
('Shalltear', 'RARE', 'main', 'Overlord'),
('Demiurge', 'RARE', 'side', 'Overlord'),
('Cocytus', 'RARE', 'side', 'Overlord'),
('Aura', 'RARE', 'side', 'Overlord'),
('Mare', 'RARE', 'side', 'Overlord'),
('Sebas', 'RARE', 'side', 'Overlord'),
('Pandora', 'RARE', 'side', 'Overlord'),
('Victim', 'RARE', 'side', 'Overlord'),

-- UNCOMMON TIER (1000 characters)
('StudentA', 'UNCOMMON', 'generic', 'Various'),
('StudentB', 'UNCOMMON', 'generic', 'Various'),
('StudentC', 'UNCOMMON', 'generic', 'Various'),
('TeacherA', 'UNCOMMON', 'generic', 'Various'),
('TeacherB', 'UNCOMMON', 'generic', 'Various'),
('NinjaA', 'UNCOMMON', 'generic', 'Various'),
('NinjaB', 'UNCOMMON', 'generic', 'Various'),
('PirateA', 'UNCOMMON', 'generic', 'Various'),
('PirateB', 'UNCOMMON', 'generic', 'Various'),
('ShinigamiA', 'UNCOMMON', 'generic', 'Various'),

-- Adding character variations
('Akira2', 'UNCOMMON', 'generic', 'Various'),
('Hiroshi2', 'UNCOMMON', 'generic', 'Various'),
('Takeshi2', 'UNCOMMON', 'generic', 'Various'),
('Kenji2', 'UNCOMMON', 'generic', 'Various'),
('Yuki2', 'UNCOMMON', 'generic', 'Various'),
('Satoshi2', 'UNCOMMON', 'generic', 'Various'),
('Ryu2', 'UNCOMMON', 'generic', 'Various'),
('Kai2', 'UNCOMMON', 'generic', 'Various'),
('Shin2', 'UNCOMMON', 'generic', 'Various'),
('Ren2', 'UNCOMMON', 'generic', 'Various'),

-- More specific character names
('Kyoya', 'UNCOMMON', 'side', 'Ouran High School'),
('Tamaki', 'UNCOMMON', 'main', 'Ouran High School'),
('Haruhi', 'UNCOMMON', 'main', 'Ouran High School'),
('Mori', 'UNCOMMON', 'side', 'Ouran High School'),
('Honey', 'UNCOMMON', 'side', 'Ouran High School'),
('Hikaru', 'UNCOMMON', 'side', 'Ouran High School'),
('Kaoru', 'UNCOMMON', 'side', 'Ouran High School'),
('Renge', 'UNCOMMON', 'side', 'Ouran High School'),
('Benio', 'UNCOMMON', 'side', 'Ouran High School'),
('Kasanoda', 'UNCOMMON', 'side', 'Ouran High School'),

-- COMMON TIER (2000+ characters)
('VillagerA', 'COMMON', 'generic', 'Various'),
('VillagerB', 'COMMON', 'generic', 'Various'),
('VillagerC', 'COMMON', 'generic', 'Various'),
('GuardA', 'COMMON', 'generic', 'Various'),
('GuardB', 'COMMON', 'generic', 'Various'),
('CitizenA', 'COMMON', 'generic', 'Various'),
('CitizenB', 'COMMON', 'generic', 'Various'),
('MerchantA', 'COMMON', 'generic', 'Various'),
('MerchantB', 'COMMON', 'generic', 'Various'),
('FarmerA', 'COMMON', 'generic', 'Various'),
('FarmerB', 'COMMON', 'generic', 'Various'),
('SoldierA', 'COMMON', 'generic', 'Various'),
('SoldierB', 'COMMON', 'generic', 'Various'),
('HunterA', 'COMMON', 'generic', 'Various'),
('HunterB', 'COMMON', 'generic', 'Various'),
('MageA', 'COMMON', 'generic', 'Various'),
('MageB', 'COMMON', 'generic', 'Various'),
('WarriorA', 'COMMON', 'generic', 'Various'),
('WarriorB', 'COMMON', 'generic', 'Various'),
('KnightA', 'COMMON', 'generic', 'Various'),

-- Common Japanese surnames
('Tanaka', 'COMMON', 'generic', 'Various'),
('Watanabe', 'COMMON', 'generic', 'Various'),
('Yoshida', 'COMMON', 'generic', 'Various'),
('Yamamoto', 'COMMON', 'generic', 'Various'),
('Matsumoto', 'COMMON', 'generic', 'Various'),
('Inoue', 'COMMON', 'generic', 'Various'),
('Kimura', 'COMMON', 'generic', 'Various'),
('Hayashi', 'COMMON', 'generic', 'Various'),
('Kato', 'COMMON', 'generic', 'Various'),
('Nakamura', 'COMMON', 'generic', 'Various'),
('Suzuki', 'COMMON', 'generic', 'Various'),
('Takahashi', 'COMMON', 'generic', 'Various'),
('Sato', 'COMMON', 'generic', 'Various'),
('Ito', 'COMMON', 'generic', 'Various'),
('Kobayashi', 'COMMON', 'generic', 'Various'),
('Saito', 'COMMON', 'generic', 'Various'),
('Kondo', 'COMMON', 'generic', 'Various'),
('Endo', 'COMMON', 'generic', 'Various'),
('Fujiwara', 'COMMON', 'generic', 'Various'),
('Mori', 'COMMON', 'generic', 'Various');

-- This provides a good foundation with ~400 unique names
-- Additional names can be added in future migrations to reach 10,000+