// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { env } from '@/config/environment';
import type { Database } from './types';

const supabaseConfig = env.getSupabaseConfig();

export const supabase = createClient<Database>(
  supabaseConfig.url,
  supabaseConfig.anonKey,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce'
    },
    global: {
      headers: {
        'x-application-name': env.get('app.name'),
        'x-application-version': env.get('app.version')
      }
    },
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    }
  }
);

// Add connection health check
export const checkSupabaseHealth = async () => {
  try {
    const { data, error } = await supabase.from('titles').select('count').limit(1);
    return { healthy: !error, error };
  } catch (e) {
    return { healthy: false, error: e };
  }
};